# Generated by Django 4.1 on 2022-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veggie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=30)),
                ('percent_discount', models.IntegerField()),
                ('price_dc', models.IntegerField()),
                ('price_sale', models.IntegerField()),
            ],
        ),
    ]
