# Generated by Django 4.1 on 2022-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veggie', '0002_product_featured_delete_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent_discount',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_dc',
            field=models.IntegerField(default=False),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
