# Generated by Django 4.1 on 2022-10-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veggie', '0003_product_percent_discount_product_price_dc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_dc',
            new_name='discounted_price',
        ),
    ]
