# Generated by Django 4.1 on 2022-10-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veggie', '0004_rename_price_dc_product_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='percent_discount',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
