# Generated by Django 4.1 on 2022-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veggie', '0005_remove_product_percent_discount_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'Vegetables'), ('FR', 'Fruit'), ('J', 'Juice'), ('DD', 'Dried')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
